image: php:7.1.1
pipelines:
  default:
    - step:
        script:
          - apt-get update && apt-get install -y unzip git
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - composer -V
          - composer install
          - curl -LSs https://box-project.github.io/box2/installer.php | php
          - php -d phar.readonly=Off box.phar build
          - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/3stadt/shopware-docker-control/downloads" --form files=@"swdc.phar"